name: Lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
   pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: "pip"
        cache-dependency-path: |
          requirements.txt

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    - name: run pre-commit
      uses: pre-commit/action@v2.0.3

   flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
            requirements.txt

    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
        pip install flake8
    - name: Lint code using flake8
      run: |
        flake8 $(git ls-files '*.py')
